/**
 * This file is autogenerated. Do not edit by hand — run `pnpm generate`.
 *
 * Non-local chain deployments live here; local (chainId 31337)
 * deployments live in `./BidVault.local.ts` (gitignored) and are merged in
 * at module load. Import by name: `import { BidVault } from "~~/contracts/BidVault";`
 */
import type { ContractDeployment } from "~~/utils/contract";
import { BidVault as BidVault_LOCAL } from "./BidVault.local";

const REMOTE = {
  11155111: {
    address: "0x60Dd6FFEfC52b6acA422163e0E4E88174c9F7F7e",
    abi: [
      {
        type: "constructor",
        inputs: [
          {
            name: "_jobRegistry",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "getBidCount",
        inputs: [
          {
            name: "jobId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getBidders",
        inputs: [
          {
            name: "jobId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "bidders",
            type: "address[]",
            internalType: "address[]",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "jobRegistry",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "submitBid",
        inputs: [
          {
            name: "jobId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "encryptedAmount",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "inputProof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "BidSubmitted",
        inputs: [
          {
            name: "jobId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "freelancer",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
    ],
    deployedOnBlock: 10805706,
  },
} as const;

export const BidVault = {
  ...REMOTE,
  ...BidVault_LOCAL,
} as const satisfies Partial<Record<number, ContractDeployment>>;
