/**
 * This file is autogenerated. Do not edit by hand — run `pnpm generate`.
 *
 * Non-local chain deployments live here; local (chainId 31337)
 * deployments live in `./BidVault.local.ts` (gitignored) and are merged in
 * at module load. Import by name: `import { BidVault } from "~~/contracts/BidVault";`
 */
import type { ContractDeployment } from "~~/utils/contract";
import { BidVault as BidVault_LOCAL } from "./BidVault.local";

const REMOTE = {
  11155111: {
    address: "0xAE23fa84931eB0b7f73Ba127f8eF06187b7E4055",
    abi: [
      {
        type: "constructor",
        inputs: [
          {
            name: "_jobRegistry",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "confidentialProtocolId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "currentLowestBidder",
        inputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getBidCount",
        inputs: [
          {
            name: "jobId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getBidders",
        inputs: [
          {
            name: "jobId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "bidders",
            type: "address[]",
            internalType: "address[]",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getEncryptedMinBid",
        inputs: [
          {
            name: "jobId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getMyBid",
        inputs: [
          {
            name: "jobId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "freelancer",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "jobRegistry",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "refundLosers",
        inputs: [
          {
            name: "jobId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "winner",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "submitBid",
        inputs: [
          {
            name: "jobId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "encryptedAmount",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "inputProof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "BidSubmitted",
        inputs: [
          {
            name: "jobId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "freelancer",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "bidIndex",
            type: "uint256",
            indexed: false,
            internalType: "uint256",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "BidsRefunded",
        inputs: [
          {
            name: "jobId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "count",
            type: "uint256",
            indexed: false,
            internalType: "uint256",
          },
        ],
        anonymous: false,
      },
      {
        type: "error",
        name: "SenderNotAllowedToUseHandle",
        inputs: [
          {
            name: "handle",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "sender",
            type: "address",
            internalType: "address",
          },
        ],
      },
      {
        type: "error",
        name: "ZamaProtocolUnsupported",
        inputs: [],
      },
    ],
    deployedOnBlock: 10751383,
  },
} as const;

export const BidVault = {
  ...REMOTE,
  ...BidVault_LOCAL,
} as const satisfies Partial<Record<number, ContractDeployment>>;
