/**
 * This file is autogenerated. Do not edit by hand — run `pnpm generate`.
 *
 * Non-local chain deployments live here; local (chainId 31337)
 * deployments live in `./JobRegistry.local.ts` (gitignored) and are merged in
 * at module load. Import by name: `import { JobRegistry } from "~~/contracts/JobRegistry";`
 */
import type { ContractDeployment } from "~~/utils/contract";
import { JobRegistry as JobRegistry_LOCAL } from "./JobRegistry.local";

const REMOTE = {
  11155111: {
    address: "0xd6a56546804d7B319DA9e7720034CB55Ada8d4c6",
    abi: [
      {
        type: "function",
        name: "escrow",
        inputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getEncryptedBudget",
        inputs: [
          {
            name: "jobId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "bytes32",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getJob",
        inputs: [
          {
            name: "jobId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "client",
            type: "address",
            internalType: "address",
          },
          {
            name: "title",
            type: "string",
            internalType: "string",
          },
          {
            name: "description",
            type: "string",
            internalType: "string",
          },
          {
            name: "deadline",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "status",
            type: "uint8",
            internalType: "enum JobRegistry.JobStatus",
          },
          {
            name: "winner",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "jobCount",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "postJob",
        inputs: [
          {
            name: "title",
            type: "string",
            internalType: "string",
          },
          {
            name: "description",
            type: "string",
            internalType: "string",
          },
          {
            name: "encryptedBudget",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "inputProof",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "deadline",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "jobId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "payable",
      },
      {
        type: "function",
        name: "releaseEscrow",
        inputs: [
          {
            name: "jobId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "selectWinner",
        inputs: [
          {
            name: "jobId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "winner",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "EscrowReleased",
        inputs: [
          {
            name: "jobId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "recipient",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "amount",
            type: "uint256",
            indexed: false,
            internalType: "uint256",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "JobPosted",
        inputs: [
          {
            name: "jobId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "client",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "title",
            type: "string",
            indexed: false,
            internalType: "string",
          },
          {
            name: "deadline",
            type: "uint256",
            indexed: false,
            internalType: "uint256",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "WinnerSelected",
        inputs: [
          {
            name: "jobId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "winner",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
    ],
    deployedOnBlock: 10805706,
  },
} as const;

export const JobRegistry = {
  ...REMOTE,
  ...JobRegistry_LOCAL,
} as const satisfies Partial<Record<number, ContractDeployment>>;
