/**
 * This file is autogenerated. Do not edit by hand — run `pnpm generate`.
 *
 * Non-local chain deployments live here; local (chainId 31337)
 * deployments live in `./ReputationLedger.local.ts` (gitignored) and are merged in
 * at module load. Import by name: `import { ReputationLedger } from "~~/contracts/ReputationLedger";`
 */
import type { ContractDeployment } from "~~/utils/contract";
import { ReputationLedger as ReputationLedger_LOCAL } from "./ReputationLedger.local";

const REMOTE = {
  11155111: {
    address: "0xDfaA5deb44b085f4f0C187c5346622b54CE8fb84",
    abi: [
      {
        type: "constructor",
        inputs: [
          {
            name: "_jobRegistry",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "confidentialProtocolId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getEncryptedEarnings",
        inputs: [
          {
            name: "freelancer",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getEncryptedRatingSum",
        inputs: [
          {
            name: "freelancer",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint32",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getPublicStats",
        inputs: [
          {
            name: "freelancer",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "ratingCount",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "completedJobs",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "jobRegistry",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "proveEarningsAbove",
        inputs: [
          {
            name: "freelancer",
            type: "address",
            internalType: "address",
          },
          {
            name: "thresholdInWei",
            type: "uint64",
            internalType: "uint64",
          },
        ],
        outputs: [
          {
            name: "result",
            type: "bytes32",
            internalType: "ebool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "proveRatingAbove",
        inputs: [
          {
            name: "freelancer",
            type: "address",
            internalType: "address",
          },
          {
            name: "threshold",
            type: "uint32",
            internalType: "uint32",
          },
        ],
        outputs: [
          {
            name: "result",
            type: "bytes32",
            internalType: "ebool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "recordEarnings",
        inputs: [
          {
            name: "freelancer",
            type: "address",
            internalType: "address",
          },
          {
            name: "encryptedEarning",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "inputProof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "submitRating",
        inputs: [
          {
            name: "freelancer",
            type: "address",
            internalType: "address",
          },
          {
            name: "encryptedRating",
            type: "bytes32",
            internalType: "externalEuint8",
          },
          {
            name: "inputProof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "EarningsUpdated",
        inputs: [
          {
            name: "freelancer",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "completedJobs",
            type: "uint256",
            indexed: false,
            internalType: "uint256",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "RatingSubmitted",
        inputs: [
          {
            name: "freelancer",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "completedJobs",
            type: "uint256",
            indexed: false,
            internalType: "uint256",
          },
        ],
        anonymous: false,
      },
      {
        type: "error",
        name: "SenderNotAllowedToUseHandle",
        inputs: [
          {
            name: "handle",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "sender",
            type: "address",
            internalType: "address",
          },
        ],
      },
      {
        type: "error",
        name: "ZamaProtocolUnsupported",
        inputs: [],
      },
    ],
    deployedOnBlock: 10805706,
  },
} as const;

export const ReputationLedger = {
  ...REMOTE,
  ...ReputationLedger_LOCAL,
} as const satisfies Partial<Record<number, ContractDeployment>>;
